### ISSUE TITLE
Implement inline stem macros using a Treeprocessor

### ISSUE THREAD

**Issue by mojavelinux** [tstumm/asciidoctor-mathematical#11]
The inline stem macros should be handled using a Treeprocessor instead of a Preprocessor. Generally, using Preprocessors should be avoided, especially for any official extension. The reason is that Preprocessors don't respect the AsciiDoc structure and can end up matching syntax that should not be interpreted.

Using a Treeprocessor does require a bit more work. You need to find all simple blocks in the tree (using find_by), then process the lines, then restore the processed lines. In other words, you are performing the inline substitution early.

If you really want to do it right, you also have to look for inline passthroughs and ignore those. But as a first attempted, I would recommend skipping that detail.

We really need to find a way in core to allow extensions to handle this macro.

**Comment by mojavelinux** [comment]
You need something roughly like:

```ruby
blocks = doc.find_by {|b| b.content_model == :simple }.each do |b|
  lines = b.lines
  # process lines
  b.lines = lines
end
```

**Comment by mojavelinux** [comment]
If the Treeprocessor approach doesn't work, then I recommend using a Postprocessor. The Preprocessor should be the last choice.

**Comment by mojavelinux** [comment]
Using my proposed approach, you can still reuse a lot of the logic you are currently using in the Preprocessor since you will still convert the inline stem macro to an image macro. You just process the lines from the Treeprocessor instead of from the Preprocessor.

**Comment by ProgramFan** [comment]
I will try this approach and it shall make handling mathematical attributes and images dir much easier for inline stems.

Just one question. @mojavelinux. Does it means that when running as a Treeprocessor, each paragraph is a un-processed single line? I read from the asciidoctor source that Treeprocessor are running on ASTs, but it seems all inline macros are not built as AST nodes.

**Comment by ProgramFan** [comment]
Nice to see this issue closed so quickly. @tstumm

**Comment by tstumm** [comment]
Well that was @mojavelinux work ;)

**Comment by mojavelinux** [comment]
> I read from the asciidoctor source that Treeprocessor are running on ASTs, but it seems all inline macros are not built as AST nodes.

That is absolutely correct. The lines of the paragraph are unprocessed at the time the Treeprocessor runs.

**Comment by mojavelinux** [comment]
I realized we may still be missing some nodes, such as the primary text of a list item. I also don't think the Treeprocessor runs on table cells yet. If I find that is the case, I'll submit a follow-up pull request.

**Comment by mojavelinux** [comment]
I've sent a pull request to process inline stem macros in list items. That covers all the lists.

What remains is to process inline stem macros in table cells. Unfortunately, `find_by` doesn't descend into table cells, so we have to go find the cells ourselves.

At some point, someone is probably going to want to process inline stem macros in section titles as well. I haven't handled that yet.

**Comment by mojavelinux** [comment]
I'm going to open separate issues for processing stem inline macros in normal table cells, AsciiDoc table cells, and section titles.
