### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by JmyL** [tstumm/asciidoctor-mathematical#5]
Dear @tstumm, I've encountered on an error when I try to use asciidoctor-mathematical, the message is like below.
```
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': liblase
m.so: cannot open shared object file: No such file or directory - /var/lib/gems/
2.2.0/extensions/x86_64-linux/2.2.0/mathematical-1.5.12/mathematical/mathematica
l.so (LoadError)
```
So I tried to compile lasem but it doesn't working.
How can I fix it?

**Comment by tstumm** [comment]
Looks like you did not install Mathematical (main dependency of asciidoctor-mathematical) properly.
Take a look at https://github.com/gjtorikian/mathematical - maybe your gem installation failed.

**Comment by tstumm** [comment]
Seems like there is an environment variable that you can set if you have already installed lasem (manually):
`MATHEMATICAL_USE_SYSTEM_LASEM=1 gem install mathematical`
Try this please.

**Comment by JmyL** [comment]
Finally I succeeded. Thanx for your help. It's superb!
