### ISSUE TITLE
Does mathematical can convert asciimath also?

### ISSUE THREAD

**Issue by JmyL** [tstumm/asciidoctor-mathematical#6]
Latex is converted well, but asciimath is not.

Asciimath is not academic but really easy to use.

**Comment by tstumm** [comment]
Well, since we are using Mathematical which only supports TeX-equations the solution is quite simple here.

If you want to implement Asciimath feel free to fork and do a pull request.

**Comment by JmyL** [comment]
It surely enough ;) I cannot handle it. Thx.
